apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portabase.fullname" . }}
  labels:
    {{- include "portabase.labels" . | nindent 4 }}
type: Opaque
stringData:
  project-secret: {{ .Values.project.secret | quote }}
